### ISSUE TITLE
Fix image overlay issue when screen size is small

### ISSUE THREAD

**Issue by bwng** [betterjournalism/betterjournalism.org#1]
Thanks to AJ for reporting this bug.

When the screen size is small (tablet sizing), the right-aligned background on the main explanatory box and the featured school box overlap with the text.

**Comment by markoet** [comment]
Moët reporting for duty.

**Comment by bwng** [comment]
@markoet wrong repository haha. You need to post to issue #1 on betterjournalism/issues

**Comment by markoet** [comment]
I get a 404 error when I go there. The original link from the email doesn't work either.
